from pandasai.helpers.telemetry import scarf_analytics
from pandasai.__version__ import __version__
import platform
from unittest.mock import patch
import os
import pytest
from unittest.mock import patch, Mock

def test_scarf_analytics_respects_no_analytics_env_var():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Test that scarf_analytics respects the SCARF_NO_ANALYTICS environment variable.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                This test checks two scenarios:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1. When SCARF_NO_ANALYTICS is set to 'true', the function should not make a request.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2. When SCARF_NO_ANALYTICS is not set, the function should make a request with the correct URL.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Set the environment variable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                os.environ['SCARF_NO_ANALYTICS'] = 'true'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Mock the requests.get function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with patch('requests.get') as mock_get:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Call the function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scarf_analytics()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Assert that requests.get was not called
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mock_get.assert_not_called()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Clean up the environment variable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                del os.environ['SCARF_NO_ANALYTICS']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Now test that it does make a request when the variable is not set
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with patch('requests.get') as mock_get:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scarf_analytics()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Assert that requests.get was called with the correct URL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expected_url = f"https://package.pandabi.ai/pandasai-telemetry?version={__version__}&platform={platform.system()}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mock_get.assert_called_once_with(expected_url)
def test_scarf_analytics_respects_do_not_track_env_var():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Test that scarf_analytics respects the DO_NOT_TRACK environment variable.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                This test checks two scenarios:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1. When DO_NOT_TRACK is set to 'true', the function should not make a request.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2. When DO_NOT_TRACK is not set, the function should make a request.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Set the environment variable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                os.environ['DO_NOT_TRACK'] = 'true'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Mock the requests.get function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with patch('requests.get') as mock_get:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Call the function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scarf_analytics()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Assert that requests.get was not called
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mock_get.assert_not_called()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Clean up the environment variable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                del os.environ['DO_NOT_TRACK']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Now test that it does make a request when the variable is not set
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with patch('requests.get') as mock_get:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scarf_analytics()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Assert that requests.get was called
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mock_get.assert_called_once()
def test_scarf_analytics_handles_exceptions():
                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                Test that scarf_analytics handles exceptions gracefully.
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                This test checks that when an exception occurs during the request,
                                                                                                                                                                                                                                                                the function catches it and doesn't raise any exception.
                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                # Mock requests.get to raise an exception
                                                                                                                                                                                                                                                                with patch('requests.get', side_effect=Exception("Test exception")):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # The function should not raise an exception
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scarf_analytics()  # This should not raise any exception
                                                                                                                                                                                                                                                                # If we reach this point without an exception, the test passes
def test_scarf_analytics_sends_correct_version_and_platform():
                                                                                                                                """
                                                                                                                                Test that scarf_analytics sends the correct version and platform information.
                                                                                                                                
                                                                                                                                This test verifies that the request URL includes the correct PandasAI version
                                                                                                                                and the current platform (operating system) when making the analytics request.
                                                                                                                                """
                                                                                                                                with patch('requests.get') as mock_get:
                                                                                                                                                                                                                                                                scarf_analytics()
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                expected_url = (
                                                                                                                                                                                                                                                                                                                                                                                                f"https://package.pandabi.ai/pandasai-telemetry?version={__version__}"
                                                                                                                                                                                                                                                                                                                                                                                                f"&platform={platform.system()}"
                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                mock_get.assert_called_once()
                                                                                                                                                                                                                                                                actual_url = mock_get.call_args[0][0]
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                assert actual_url == expected_url, (
                                                                                                                                                                                                                                                                                                                                                                                                f"Expected URL: {expected_url}\n"
                                                                                                                                                                                                                                                                                                                                                                                                f"Actual URL: {actual_url}"
                                                                                                                                                                                                                                                                )
def test_scarf_analytics_respects_both_env_vars():
                                                                """
                                                                Test that scarf_analytics respects both SCARF_NO_ANALYTICS and DO_NOT_TRACK
                                                                environment variables when they are set simultaneously.
                                                                This test checks that when both SCARF_NO_ANALYTICS and DO_NOT_TRACK are set to 'true',
                                                                the function does not make a request, regardless of the order they are set.
                                                                """
                                                                # Set both environment variables
                                                                os.environ['SCARF_NO_ANALYTICS'] = 'true'
                                                                os.environ['DO_NOT_TRACK'] = 'true'
                                                                # Mock the requests.get function
                                                                with patch('requests.get') as mock_get:
                                                                                                                                # Call the function
                                                                                                                                scarf_analytics()
                                                                                                                                # Assert that requests.get was not called
                                                                                                                                mock_get.assert_not_called()
                                                                # Clean up the environment variables
                                                                del os.environ['SCARF_NO_ANALYTICS']
                                                                del os.environ['DO_NOT_TRACK']
                                                                # Now set the variables in reverse order
                                                                os.environ['DO_NOT_TRACK'] = 'true'
                                                                os.environ['SCARF_NO_ANALYTICS'] = 'true'
                                                                # Mock the requests.get function again
                                                                with patch('requests.get') as mock_get:
                                                                                                                                # Call the function
                                                                                                                                scarf_analytics()
                                                                                                                                # Assert that requests.get was still not called
                                                                                                                                mock_get.assert_not_called()
                                                                # Clean up the environment variables again
                                                                del os.environ['DO_NOT_TRACK']
                                                                del os.environ['SCARF_NO_ANALYTICS']
def test_scarf_analytics_with_mixed_env_vars():
                                """
                                Test that scarf_analytics behaves correctly when one environment variable
                                is set to 'true' and the other is set to a different value.
                                
                                This test checks two scenarios:
                                1. When SCARF_NO_ANALYTICS is 'true' and DO_NOT_TRACK is 'false'
                                2. When SCARF_NO_ANALYTICS is 'false' and DO_NOT_TRACK is 'true'
                                
                                In both cases, the function should not make a request.
                                """
                                # Scenario 1: SCARF_NO_ANALYTICS is 'true' and DO_NOT_TRACK is 'false'
                                os.environ['SCARF_NO_ANALYTICS'] = 'true'
                                os.environ['DO_NOT_TRACK'] = 'false'
                                
                                with patch('requests.get') as mock_get:
                                                                scarf_analytics()
                                                                mock_get.assert_not_called()
                                
                                # Clean up environment variables
                                del os.environ['SCARF_NO_ANALYTICS']
                                del os.environ['DO_NOT_TRACK']
                                
                                # Scenario 2: SCARF_NO_ANALYTICS is 'false' and DO_NOT_TRACK is 'true'
                                os.environ['SCARF_NO_ANALYTICS'] = 'false'
                                os.environ['DO_NOT_TRACK'] = 'true'
                                
                                with patch('requests.get') as mock_get:
                                                                scarf_analytics()
                                                                mock_get.assert_not_called()
                                
                                # Clean up environment variables
                                del os.environ['SCARF_NO_ANALYTICS']
                                del os.environ['DO_NOT_TRACK']
def test_scarf_analytics_with_non_boolean_env_vars():
                """
                Test that scarf_analytics behaves correctly when environment variables
                are set to non-boolean string values.
                
                This test checks the following scenarios:
                1. When SCARF_NO_ANALYTICS is set to a non-'true' string
                2. When DO_NOT_TRACK is set to a non-'true' string
                
                In both cases, the function should make a request as these values
                are not interpreted as True.
                """
                # Scenario 1: SCARF_NO_ANALYTICS is set to a non-'true' string
                os.environ['SCARF_NO_ANALYTICS'] = 'yes'
                
                with patch('requests.get') as mock_get:
                                scarf_analytics()
                                mock_get.assert_called_once()
                
                # Clean up environment variable
                del os.environ['SCARF_NO_ANALYTICS']
                
                # Scenario 2: DO_NOT_TRACK is set to a non-'true' string
                os.environ['DO_NOT_TRACK'] = 'on'
                
                with patch('requests.get') as mock_get:
                                scarf_analytics()
                                mock_get.assert_called_once()
                
                # Clean up environment variable
                del os.environ['DO_NOT_TRACK']
def test_scarf_analytics_with_non_200_response():
        """
        Test that scarf_analytics handles a non-200 response correctly.
        
        This test verifies that when the analytics request returns a non-200 status code,
        the function completes without raising an exception and makes the correct request.
        """
        mock_response = Mock()
        mock_response.status_code = 404  # Set a non-200 status code
        with patch('requests.get', return_value=mock_response) as mock_get:
                scarf_analytics()  # This should not raise any exception
                # Verify that the request was made with the correct URL
                expected_url = f"https://package.pandabi.ai/pandasai-telemetry?version={__version__}&platform={platform.system()}"
                mock_get.assert_called_once_with(expected_url)
        # If we reach this point without an exception, the test passes